// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],*/

  docSidebar: [
    'README',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      items: [
        'getting-started/introduction',
        'getting-started/getting-started-with-j2store',
        'getting-started/technical-requirements',
        'getting-started/installation',
        'getting-started/update',
        'getting-started/upgrade-free-version-to-pro-version',
      ],
    },
    'migration-from-j2store-3-to-4',
    {
      type: 'category',
      label: 'Set Up',
      link: {
        type: 'generated-index',
      },
      items: [
        'set-up/content-plugin-settings',
        'set-up/configuration',
        'set-up/currency',
        'set-up/custom-fields',
        'set-up/setup-multi-currency',
      ],
    },
    'quick-start-guide',
    {
      type: 'category',
      label: 'Product Types',
      link: {
        type: 'generated-index',
      },
      items: [
        'product-types/simple-product',
        'product-types/variable-product',
        'product-types/configurable-product',
        'product-types/flexible-variable-product',
        'product-types/downloadable-product',
      ],
    },
    {
      type: 'category',
      label: 'Layouts',
      link: {
        type: 'generated-index',
      },
      items: [
        'layout/product-layout',
        'layout/product-tag-layout',
        'layout/usecases',
        'layout/category-tree-for-displaying-filters',
        'layout/special-module-positions',
      ],
    },
    {
      type: 'category',
      label: 'Catalog',
      link: {
        type: 'generated-index',
      },
      items: [
        'catalog/assigning-a-product-to-multiple-categories',
        'catalog/product-description',
        'catalog/short-codes',
        'catalog/adding-specifications-to-your-products',
        'catalog/advanced-pricing',
        'catalog/setting-up-tax-for-your-products',
        {
          type: 'category',
          label: 'Options',
          link: {
            type: 'doc',
            id: 'catalog/options/index',
          },
          items: [
            'catalog/options/import-product-options',
            'catalog/options/how-to-create-options-and-add-them-to-your-products',
          ],
        },
        {
          type: 'category',
          label: 'Filters',
          link: {
            type: 'generated-index',
          },
          items: [
            'catalog/filters/product-filters',
            'catalog/filters/translating-filters-to-your-language',
          ],
        },
        'catalog/manufacturers',
        'catalog/vendors',
        'catalog/adding-related-products',
        'catalog/ordering-products-on-your-storefront',
      ],
    },
    {
      type: 'category',
      label: 'Subscriptions and Memberships',
      link: {
        type: 'generated-index',
      },
      items: [
        'subscriptions-and-memberships/introduction-to-subscriptions-and-memberships-in-j2store',
        'subscriptions-and-memberships/quickstart',
        'subscriptions-and-memberships/requirements-and-installation',
        'subscriptions-and-memberships/basic-settings',
        'subscriptions-and-memberships/creating-subscription-based-products',
        'subscriptions-and-memberships/simple-subscription-product',
        'subscriptions-and-memberships/paypal-refrence-transactions-for-subscriptions',
        'subscriptions-and-memberships/usecases',
        'subscriptions-and-memberships/customizing-the-subscription-mail-templates',
        'subscriptions-and-memberships/frequently-asked-questions',
      ],
    },
    {
      type: 'category',
      label: 'Partial Payments',
      link: {
        type: 'generated-index',
      },
      items: [
        'partial-payments/introduction-to-partial-payments',
        'partial-payments/basic-settings',
        'partial-payments/setting-up-plans-for-partial-payments',
        'partial-payments/instances',
        'partial-payments/usecases',
      ],
    },
    {
      type: 'category',
      label: 'Booking and Reservations',
      link: {
        type: 'generated-index',
      },
      items: [
        'booking-and-reservations/limitation-of-the-booking-products-type',
        'booking-and-reservations/requirements-and-installation',
        'booking-and-reservations/basic-settings-and-booking-management',
        'booking-and-reservations/booking-and-reservations',
        'booking-and-reservations/creating-a-bookable-product',
        'booking-and-reservations/how-to-restrict-multiple-booking-for-a-product-person-based-restriction',
        'booking-and-reservations/usecases',
      ],
    },
    'localisation',
    {
      type: 'category',
      label: 'Translation',
      link: {
        type: 'generated-index',
      },
      items: [
        'translation/translate-j2store-into-your-language',
        'translation/setting-up-the-store-in-your-language',
        'translation/how-to-write-language-override-for-plugin-in-multilingual-site',
        'translation/language-overrides-in-joomla-with-examples',
        'translation/translating-product-options',
      ],
    },
    {
      type: 'category',
      label: 'Design',
      link: {
        type: 'generated-index',
      },
      items: [
        'design/email-templates',
        'design/invoice-template-pro-feature',
      ],
    },
    {
      type: 'category',
      label: 'Tax Configuration',
      link: {
        type: 'generated-index',
      },
      items: [
        'tax-configuration/recommended-tax-configuration-for-us-states',
        'tax-configuration/recommended-tax-configuration-for-canadian-stores',
        'tax-configuration/recommended-tax-configuration-for-eu-stores',
        'tax-configuration/setting-up-european-vat-rules-for-selling-physical-goods-with-j2store',
        'tax-configuration/a-simplified-guide-for-new-eu-vat-rules-2015-for-digital-goods-and-setting-them-up-in-j2store',
        'tax-configuration/how-tax-is-calculated',
      ],
    },
    {
      type: 'category',
      label: 'Easy Checkout',
      link: {
        type: 'generated-index',
      },
      items: [
        'easy-checkout/easy-checkout',
        'easy-checkout/trouble-shooting-easy-checkout',
      ],
    },
    {
      type: 'category',
      label: 'Sales',
      link: {
        type: 'generated-index',
      },
      items: [
        'sales/coupons',
        'sales/vouchers',
        'sales/customers',
        'sales/orders',
      ],
    },
    'report-sales',
    {
      type: 'category',
      label: 'Shipping Methods',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'shipping-methods',
        },
      ],
    },
    {
      type: 'category',
      label: 'Payment Methods',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'payment-methods',
        },
      ],
    },
    {
      type: 'category',
      label: 'Apps',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'apps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plugins',
        },
      ],
    },
    {
      type: 'category',
      label: 'Frequently Asked Questions',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'frequently-asked-questions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting Guide',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting-guide',
        },
      ],
    },
    {
      type: 'category',
      label: 'Common Overrides',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'common-overrides',
        },
      ],
    },
    {
      type: 'category',
      label: 'General',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'general',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      link: {
        type: 'generated-index',
      },
      items: [
        'developer-guide/introduction',
        'developer-guide/queue-system',
        'developer-guide/app-for-j2store',
        'developer-guide/sub-templates',
        'developer-guide/creating-an-integration-plugin-for-your-component',
        'developer-guide/payment-plugin',
        'developer-guide/templates',
      ],
    },
  ],
};

export default sidebars;
